/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laundryservice;

import com.mycompany.laundryservice.panels.SidebarPanel;
import java.awt.FontFormatException;
import java.io.IOException;

/**
 *
 * @author Cral
 */
public class MainJFrame extends javax.swing.JFrame {

	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJFrame.class.getName());

	/**
	 * Creates new form MainJFrame
	 */
	public MainJFrame() {
		initComponents();
		setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

		sidebarPanel1.setMainFrame(this);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                sidebarPanel1 = new com.mycompany.laundryservice.panels.SidebarPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().add(sidebarPanel1, java.awt.BorderLayout.LINE_START);

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	private static void ensureSingleInstance() {
		try {
			try (java.net.Socket clientSocket = new java.net.Socket("127.0.0.1", 12345)) {
				java.io.PrintWriter out = new java.io.PrintWriter(clientSocket.getOutputStream(), true);
				out.println("SHUTDOWN");
				Thread.sleep(500); 
			}
		} catch (Exception e) {
		}

		new Thread(() -> {
			try (java.net.ServerSocket serverSocket = new java.net.ServerSocket(12345)) {
				while (true) {
					try (java.net.Socket socket = serverSocket.accept(); java.io.BufferedReader in = new java.io.BufferedReader(new java.io.InputStreamReader(socket.getInputStream()))) {

						if ("SHUTDOWN".equals(in.readLine())) {
							System.exit(0);
						}
					}
				}
			} catch (Exception ex) {
			}
		}).start();
	}

	public static void main(String args[]) {
		ensureSingleInstance();

		com.formdev.flatlaf.FlatLightLaf.setup();

		try {
			java.awt.GraphicsEnvironment ge = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();

			java.io.InputStream isReg = MainJFrame.class.getResourceAsStream("/fonts/Inter_18pt-Regular.ttf");
			if (isReg != null) {
				ge.registerFont(java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, isReg));
			}

			java.io.InputStream isMedium = MainJFrame.class.getResourceAsStream("/font/Inter_18pt-Medium.ttf");
			if (isMedium != null) {
				ge.registerFont(java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, isMedium));
			}

			java.io.InputStream isSemiBold = MainJFrame.class.getResourceAsStream("/font/Inter_18pt-SemiBold.ttf");
			if (isSemiBold != null) {
				ge.registerFont(java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, isSemiBold));
			}

			java.io.InputStream isBold = MainJFrame.class.getResourceAsStream("/fonts/Inter_18pt-Bold.ttf");
			if (isBold != null) {
				ge.registerFont(java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, isBold));
			}

			java.io.InputStream is28Bold = MainJFrame.class.getResourceAsStream("/fonts/Inter_28pt-Bold.ttf");
			if (is28Bold != null) {
				ge.registerFont(java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, is28Bold));
			}

			java.io.InputStream isPlayfair = MainJFrame.class.getResourceAsStream("/fonts/PlayfairDisplay-Bold.ttf");
			if (isPlayfair != null) {
				ge.registerFont(java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, isPlayfair));
			}

		} catch (FontFormatException | IOException e) {
			System.err.println("Warning: Failed to load custom fonts");
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new MainJFrame().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private com.mycompany.laundryservice.panels.SidebarPanel sidebarPanel1;
        // End of variables declaration//GEN-END:variables
}
