/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laundryservice.panels;

import javax.swing.JFrame;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.BorderFactory;
/**
 *
 * @author Cral
 */
public class CustomerPanel extends javax.swing.JPanel {

	/**
	 * Creates new form CustomerPanel
	 */
	public CustomerPanel() {
		initComponents();
                applyDesignStyling();
                txtSearch.putClientProperty("JTextField.leadingIcon", loadIcon("search.svg", 16, 0x434654));
                btnSave.setIcon(loadIcon("save.svg", 18, 0xFFFFFF));
                btnUpdate.setIcon(loadIcon("edit.svg", 18, 0xFFFFFF));
                btnDeactivate.setIcon(loadIcon("person_off.svg", 18, 0xFFFFFF));
                btnFilter.setIcon(loadIcon("filter_list.svg", 18, 0x434654));
                lblRegisterHeader.setIcon(loadIcon("person_add.svg", 20, 0x33CCF9));
                txtName.putClientProperty("JTextField.placeholderText", "Enter Customer Name");
                txtPhone.putClientProperty("JTextField.placeholderText", "+63 900 000 0000");
                txtAddress.putClientProperty("JTextField.placeholderText", "Street, Barangay, City");
                txtSearch.putClientProperty("JTextField.placeholderText", "Search by name, ID, or phone number...");
        }
        private javax.swing.Icon loadIcon(String iconName, int size, int colorHex) {
            com.formdev.flatlaf.extras.FlatSVGIcon icon =
                    new com.formdev.flatlaf.extras.FlatSVGIcon("icons/" + iconName, size, size);
            icon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(c -> new Color(colorHex)));
            return icon;
        }
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlRegisterCard = new javax.swing.JPanel();
        lblRegisterHeader = new javax.swing.JLabel();
        lblNameCaption = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPhoneCaption = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblAddressCaption = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        pnlSearchBar = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        pnlTableCard = new javax.swing.JPanel();
        scrollCustomers = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        lblRecordCount = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();
        pnlStats = new javax.swing.JPanel();
        lblTotalCustomersCaption = new javax.swing.JLabel();
        lblTotalCustomersValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(249, 249, 249));

        lblTitle.setFont(new java.awt.Font("Inter 28pt", 0, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(26, 28, 28));
        lblTitle.setText("Customer Management");

        lblSubtitle.setFont(new java.awt.Font("Inter 18pt", 0, 11)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(67, 70, 84));
        lblSubtitle.setText("Register, search, and manage customer records for your laundry service.");

        pnlRegisterCard.setBackground(new java.awt.Color(255, 255, 255));

        lblRegisterHeader.setFont(new java.awt.Font("Inter 28pt", 0, 18)); // NOI18N
        lblRegisterHeader.setText("Register New Customer");

        lblNameCaption.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 11)); // NOI18N
        lblNameCaption.setText("Full Name");

        txtName.setFont(new java.awt.Font("Inter 18pt", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 0, 0));

        lblPhoneCaption.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 11)); // NOI18N
        lblPhoneCaption.setText("Phone Number");

        txtPhone.setFont(new java.awt.Font("Inter 18pt", 0, 12)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(0, 0, 0));

        lblAddressCaption.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 11)); // NOI18N
        lblAddressCaption.setText("Home Address");

        txtAddress.setFont(new java.awt.Font("Inter 18pt", 0, 12)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 0, 0));

        btnSave.setBackground(new java.awt.Color(51, 204, 249));
        btnSave.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Customer");

        javax.swing.GroupLayout pnlRegisterCardLayout = new javax.swing.GroupLayout(pnlRegisterCard);
        pnlRegisterCard.setLayout(pnlRegisterCardLayout);
        pnlRegisterCardLayout.setHorizontalGroup(
            pnlRegisterCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlRegisterCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddressCaption)
                    .addComponent(txtAddress)
                    .addComponent(lblPhoneCaption)
                    .addComponent(txtPhone)
                    .addComponent(lblRegisterHeader)
                    .addComponent(lblNameCaption)
                    .addComponent(txtName)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlRegisterCardLayout.setVerticalGroup(
            pnlRegisterCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterCardLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblRegisterHeader)
                .addGap(18, 18, 18)
                .addComponent(lblNameCaption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhoneCaption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAddressCaption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pnlSearchBar.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.setBackground(new java.awt.Color(249, 249, 249));
        txtSearch.setFont(new java.awt.Font("Inter 18pt", 0, 12)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.setBorder(null);
        txtSearch.addActionListener(this::txtSearchActionPerformed);

        btnFilter.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 12)); // NOI18N
        btnFilter.setText("Filter");
        btnFilter.addActionListener(this::btnFilterActionPerformed);

        javax.swing.GroupLayout pnlSearchBarLayout = new javax.swing.GroupLayout(pnlSearchBar);
        pnlSearchBar.setLayout(pnlSearchBarLayout);
        pnlSearchBarLayout.setHorizontalGroup(
            pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtSearch)
                .addGap(18, 18, 18)
                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlSearchBarLayout.setVerticalGroup(
            pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtSearch))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlTableCard.setBackground(new java.awt.Color(255, 255, 255));

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone", "Address", "Active", "Created At"
            }
        ));
        scrollCustomers.setViewportView(tblCustomers);

        lblRecordCount.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 11)); // NOI18N
        lblRecordCount.setText("Showing 5 of 1,284 customers");

        javax.swing.GroupLayout pnlTableCardLayout = new javax.swing.GroupLayout(pnlTableCard);
        pnlTableCard.setLayout(pnlTableCardLayout);
        pnlTableCardLayout.setHorizontalGroup(
            pnlTableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableCardLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlTableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRecordCount)
                    .addComponent(scrollCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlTableCardLayout.setVerticalGroup(
            pnlTableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(scrollCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRecordCount)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnUpdate.setBackground(new java.awt.Color(38, 85, 189));
        btnUpdate.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Details");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDeactivate.setBackground(new java.awt.Color(186, 26, 26));
        btnDeactivate.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 12)); // NOI18N
        btnDeactivate.setForeground(new java.awt.Color(255, 255, 255));
        btnDeactivate.setText("Deactivate");

        pnlStats.setBackground(new java.awt.Color(238, 240, 246));

        lblTotalCustomersCaption.setFont(new java.awt.Font("Inter 18pt", 0, 10)); // NOI18N
        lblTotalCustomersCaption.setText("Total Customers");

        lblTotalCustomersValue.setFont(new java.awt.Font("Inter 18pt", 1, 14)); // NOI18N
        lblTotalCustomersValue.setText("1,284");

        javax.swing.GroupLayout pnlStatsLayout = new javax.swing.GroupLayout(pnlStats);
        pnlStats.setLayout(pnlStatsLayout);
        pnlStatsLayout.setHorizontalGroup(
            pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalCustomersValue)
                    .addComponent(lblTotalCustomersCaption))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStatsLayout.setVerticalGroup(
            pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTotalCustomersCaption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalCustomersValue)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblSubtitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlRegisterCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlTableCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlRegisterCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlTableCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applyDesignStyling() {
    Color cardStroke = new Color(0xC3, 0xC6, 0xD7);

    // Rounded, bordered cards (real rounding via custom border)
    pnlRegisterCard.setOpaque(false);
    pnlRegisterCard.setBorder(new RoundedCardBorder(16, Color.WHITE, cardStroke));

    pnlSearchBar.setOpaque(false);
    pnlSearchBar.setBorder(new RoundedCardBorder(16, Color.WHITE, cardStroke));

    pnlTableCard.setOpaque(false);
    pnlTableCard.setBorder(new RoundedCardBorder(16, Color.WHITE, cardStroke));

}
    
private static class RoundedCardBorder extends javax.swing.border.AbstractBorder {
    private final int radius;
    private final Color fill;
    private final Color stroke;

    RoundedCardBorder(int radius, Color fill, Color stroke) {
        this.radius = radius;
        this.fill = fill;
        this.stroke = stroke;
    }

    @Override
    public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(java.awt.RenderingHints.KEY_STROKE_CONTROL, java.awt.RenderingHints.VALUE_STROKE_PURE);

        // Fill covers the full card area
        g2.setColor(fill);
        g2.fillRoundRect(x, y, width - 1, height - 1, radius, radius);

        // Stroke drawn as a shape inset by 0.5px so it's never clipped on any edge
        g2.setColor(stroke);
        g2.setStroke(new java.awt.BasicStroke(1f));
        java.awt.geom.RoundRectangle2D.Float shape = new java.awt.geom.RoundRectangle2D.Float(
                x + 0.5f, y + 0.5f, width - 1.5f, height - 1.5f, radius, radius);
        g2.draw(shape);

        g2.dispose();
    }

    @Override
    public java.awt.Insets getBorderInsets(java.awt.Component c) {
        return new java.awt.Insets(0, 0, 0, 0);
    }
}
     
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAddressCaption;
    private javax.swing.JLabel lblNameCaption;
    private javax.swing.JLabel lblPhoneCaption;
    private javax.swing.JLabel lblRecordCount;
    private javax.swing.JLabel lblRegisterHeader;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCustomersCaption;
    private javax.swing.JLabel lblTotalCustomersValue;
    private javax.swing.JPanel pnlRegisterCard;
    private javax.swing.JPanel pnlSearchBar;
    private javax.swing.JPanel pnlStats;
    private javax.swing.JPanel pnlTableCard;
    private javax.swing.JScrollPane scrollCustomers;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
