package com.mycompany.laundryservice.panels;

import javax.swing.JFrame;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.BorderFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.ListSelectionModel;
import java.awt.Font;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

public class CustomerPanel extends javax.swing.JPanel {
        private int selectedCustomerId = -1;
        private boolean editMode = false;
        private boolean selectedIsActive = true;
        private boolean showingDeactivated = false;
	public CustomerPanel() {
		initComponents();
                applyDesignStyling();
                formatCustomerTable();
                loadCustomers("");
                updateCustomerCount();
                attachTableSelectionListener();
                txtName.putClientProperty("JTextField.placeholderText", "Enter Customer Name");
                txtPhone.putClientProperty("JTextField.placeholderText", "+63 900 000 0000");
                txtAddress.putClientProperty("JTextField.placeholderText", "Street, Barangay, City");
                txtSearch.putClientProperty("JTextField.placeholderText", "Search by name, ID, or phone number...");
                btnSave.setIcon(loadIcon("save.svg", 18, 0x1A1C1C));
                btnUpdate.setIcon(loadIcon("edit.svg", 18, 0xFFFFFF));
                btnDeactivate.setIcon(loadIcon("person_off.svg", 18, 0xFFFFFF));
                btnFilter.setIcon(loadIcon("filter_list.svg", 18, 0x434654));
                lblRegisterHeader.setIcon(loadIcon("person_add.svg", 20, 0x33CCF9));
                txtSearch.putClientProperty("JTextField.leadingIcon", loadIcon("search.svg", 16, 0x434654));
                lblTotalCustomersValue.setIcon(loadIcon("group.svg", 18, 0x2655BD));
                lblTotalCustomersValue.setIconTextGap(6);
        }
        
        private javax.swing.Icon loadIcon(String iconName, int size, int colorHex) {
            com.formdev.flatlaf.extras.FlatSVGIcon icon =
            new com.formdev.flatlaf.extras.FlatSVGIcon("icons/" + iconName, size, size);
            icon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(c -> new Color(colorHex)));
        return icon;
}
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        pnlStats = new javax.swing.JPanel();
        lblTotalCustomersCaption = new javax.swing.JLabel();
        lblTotalCustomersValue = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        pnlSearchBar = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        pnlRegisterCard = new javax.swing.JPanel();
        lblRegisterHeader = new javax.swing.JLabel();
        lblNameCaption = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPhoneCaption = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblAddressCaption = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblRegisterHint = new javax.swing.JLabel();
        pnlTableCard = new javax.swing.JPanel();
        scrollCustomers = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        lblRecordCount = new javax.swing.JLabel();
        btnDeactivatedAccounts = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 249, 249));

        pnlHeader.setBackground(new java.awt.Color(249, 249, 249));

        lblTitle.setFont(new java.awt.Font("Inter 28pt", 0, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(26, 28, 28));
        lblTitle.setText("Customer Management");

        lblSubtitle.setFont(new java.awt.Font("Inter 18pt", 0, 14)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(67, 70, 84));
        lblSubtitle.setText("Register, search, and manage customer records for your laundry service.");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblSubtitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlBody.setBackground(new java.awt.Color(249, 249, 249));

        pnlStats.setBackground(new java.awt.Color(255, 255, 255));

        lblTotalCustomersCaption.setFont(new java.awt.Font("Inter 18pt", 0, 10)); // NOI18N
        lblTotalCustomersCaption.setText("Customers");

        lblTotalCustomersValue.setFont(new java.awt.Font("Inter 18pt", 1, 14)); // NOI18N
        lblTotalCustomersValue.setText("0");

        lblStatus.setFont(new java.awt.Font("Inter 18pt", 0, 10)); // NOI18N

        javax.swing.GroupLayout pnlStatsLayout = new javax.swing.GroupLayout(pnlStats);
        pnlStats.setLayout(pnlStatsLayout);
        pnlStatsLayout.setHorizontalGroup(
            pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalCustomersValue)
                    .addComponent(lblTotalCustomersCaption))
                .addGap(18, 18, 18)
                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlStatsLayout.setVerticalGroup(
            pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlStatsLayout.createSequentialGroup()
                        .addComponent(lblTotalCustomersCaption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalCustomersValue)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlSearchBar.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.setBackground(new java.awt.Color(249, 249, 249));
        txtSearch.setFont(new java.awt.Font("Inter 18pt", 0, 12)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.setBorder(null);
        txtSearch.addActionListener(this::txtSearchActionPerformed);

        btnFilter.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 12)); // NOI18N
        btnFilter.setText("Filter");
        btnFilter.addActionListener(this::btnFilterActionPerformed);

        javax.swing.GroupLayout pnlSearchBarLayout = new javax.swing.GroupLayout(pnlSearchBar);
        pnlSearchBar.setLayout(pnlSearchBarLayout);
        pnlSearchBarLayout.setHorizontalGroup(
            pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlSearchBarLayout.setVerticalGroup(
            pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtSearch))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlRegisterCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegisterCard.setPreferredSize(new java.awt.Dimension(269, 351));

        lblRegisterHeader.setFont(new java.awt.Font("Inter 28pt", 0, 18)); // NOI18N
        lblRegisterHeader.setText("Register New Customer");

        lblNameCaption.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 11)); // NOI18N
        lblNameCaption.setText("Full Name");

        txtName.setFont(new java.awt.Font("Inter 18pt", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 0, 0));

        lblPhoneCaption.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 11)); // NOI18N
        lblPhoneCaption.setText("Phone Number");

        txtPhone.setFont(new java.awt.Font("Inter 18pt", 0, 12)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(0, 0, 0));
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });

        lblAddressCaption.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 11)); // NOI18N
        lblAddressCaption.setText("Home Address");

        txtAddress.setFont(new java.awt.Font("Inter 18pt", 0, 12)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 0, 0));

        btnSave.setBackground(new java.awt.Color(51, 204, 249));
        btnSave.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(26, 28, 28));
        btnSave.setText("Save Customer");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        lblRegisterHint.setFont(new java.awt.Font("Inter 18pt", 0, 9)); // NOI18N
        lblRegisterHint.setForeground(new java.awt.Color(67, 70, 84));
        lblRegisterHint.setText("Select a customer from the table to update their information.");

        javax.swing.GroupLayout pnlRegisterCardLayout = new javax.swing.GroupLayout(pnlRegisterCard);
        pnlRegisterCard.setLayout(pnlRegisterCardLayout);
        pnlRegisterCardLayout.setHorizontalGroup(
            pnlRegisterCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlRegisterCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegisterHint)
                    .addGroup(pnlRegisterCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblAddressCaption)
                        .addComponent(txtAddress)
                        .addComponent(lblPhoneCaption)
                        .addComponent(txtPhone)
                        .addComponent(lblRegisterHeader)
                        .addComponent(lblNameCaption)
                        .addComponent(txtName)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegisterCardLayout.setVerticalGroup(
            pnlRegisterCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterCardLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblRegisterHeader)
                .addGap(1, 1, 1)
                .addComponent(lblRegisterHint)
                .addGap(7, 7, 7)
                .addComponent(lblNameCaption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhoneCaption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAddressCaption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pnlTableCard.setBackground(new java.awt.Color(255, 255, 255));

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone", "Address", "Active", "Created At"
            }
        ));
        scrollCustomers.setViewportView(tblCustomers);

        lblRecordCount.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 11)); // NOI18N
        lblRecordCount.setText("Showing 5 of 1,284 customers");

        btnDeactivatedAccounts.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 12)); // NOI18N
        btnDeactivatedAccounts.setText("Show Deactivated Accounts");
        btnDeactivatedAccounts.addActionListener(this::btnDeactivatedAccountsActionPerformed);

        javax.swing.GroupLayout pnlTableCardLayout = new javax.swing.GroupLayout(pnlTableCard);
        pnlTableCard.setLayout(pnlTableCardLayout);
        pnlTableCardLayout.setHorizontalGroup(
            pnlTableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlTableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTableCardLayout.createSequentialGroup()
                        .addComponent(lblRecordCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeactivatedAccounts))
                    .addComponent(scrollCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        pnlTableCardLayout.setVerticalGroup(
            pnlTableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(scrollCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeactivatedAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecordCount))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnUpdate.setBackground(new java.awt.Color(38, 85, 189));
        btnUpdate.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Details");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDeactivate.setBackground(new java.awt.Color(186, 26, 26));
        btnDeactivate.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 12)); // NOI18N
        btnDeactivate.setForeground(new java.awt.Color(255, 255, 255));
        btnDeactivate.setText("Deactivate");
        btnDeactivate.addActionListener(this::btnDeactivateActionPerformed);

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRegisterCard, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(pnlStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlTableCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(pnlSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlTableCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(pnlRegisterCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void attachTableSelectionListener() {
    tblCustomers.getSelectionModel().addListSelectionListener(e -> {
        if (e.getValueIsAdjusting()) return;

        int row = tblCustomers.getSelectedRow();
        if (row == -1) return;

        selectedCustomerId = (int) tblCustomers.getValueAt(row, 0);
        lblRegisterHeader.setText("Update Customer");
        btnSave.setText("Update Customer");
        txtName.setText(String.valueOf(tblCustomers.getValueAt(row, 1)));
        txtPhone.setText(String.valueOf(tblCustomers.getValueAt(row, 2)));
        Object addr = tblCustomers.getValueAt(row, 3);
        txtAddress.setText(addr == null ? "" : String.valueOf(addr));

        btnUpdate.setEnabled(true);
        btnDeactivate.setEnabled(true);
        
        editMode = true;
        lblRegisterHeader.setText("Update Information");
        lblRegisterHint.setText(
            "Update the selected customer's information."
        );
        btnSave.setText("Update Customer");
        btnSave.setIcon(loadIcon("edit.svg", 18, 0x1A1C1C));

        String activeStatus = String.valueOf(tblCustomers.getValueAt(row, 4));
        selectedIsActive = "Active".equals(activeStatus);
        updateDeactivateButtonLabel();
    });
    }
    
    private void updateDeactivateButtonLabel() {
        if (selectedIsActive) {
            btnDeactivate.setText("Deactivate");
            btnDeactivate.setBackground(new Color(0xBA, 0x1A, 0x1A));
        } else {
            btnDeactivate.setText("Activate");
            btnDeactivate.setBackground(new Color(0x2E, 0x7D, 0x32));
        }
    }
    
    private void applyDesignStyling() {
    Color cardStroke = new Color(0xC3, 0xC6, 0xD7);

    // Rounded, bordered cards (real rounding via custom border)
    pnlRegisterCard.setOpaque(false);
    pnlRegisterCard.setBorder(new RoundedCardBorder(16, Color.WHITE, cardStroke));

    pnlSearchBar.setOpaque(false);
    pnlSearchBar.setBorder(new RoundedCardBorder(16, Color.WHITE, cardStroke));

    pnlTableCard.setOpaque(false);
    pnlTableCard.setBorder(new RoundedCardBorder(16, Color.WHITE, cardStroke));
    
    pnlStats.setOpaque(false);
    pnlStats.setBorder(new RoundedCardBorder(16, Color.WHITE, cardStroke));
    }  
    

    private void formatCustomerTable() {
    tblCustomers.setShowVerticalLines(false);
    tblCustomers.setShowHorizontalLines(true);
    tblCustomers.setGridColor(new Color(0xC3, 0xC6, 0xD7));
    tblCustomers.setRowHeight(48);

    tblCustomers.getTableHeader().setFont(
            new Font("Inter 18pt", Font.BOLD, 14));

    tblCustomers.setFont(
            new Font("Inter 18pt", Font.PLAIN, 14));

    DefaultTableCellRenderer claimRenderer = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(
                JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {

            super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            setFont(new Font("Inter 18pt", Font.BOLD, 14));

            if (isSelected) {
                setForeground(Color.WHITE);
            } else {
                setForeground(new Color(0x2655BD));
            }

            setHorizontalAlignment(SwingConstants.CENTER);

            return this;
        }
    };

    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

    tblCustomers.getColumnModel().getColumn(0).setCellRenderer(claimRenderer);

    for (int i = 1; i < tblCustomers.getColumnCount(); i++) {
        tblCustomers.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
    }

    tblCustomers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}
        private void loadCustomers(String searchTerm) {
            DefaultTableModel model = new DefaultTableModel(
                    new String[]{"ID", "Name", "Phone", "Address", "Active", "Created At"}, 0) {
                @Override
                public boolean isCellEditable(int row, int column) { return false; }
            };

            String sql;
            if (showingDeactivated) {
                sql = "SELECT customer_id, name, phone, address, is_active, created_at "
                    + "FROM Customers "
                    + "WHERE is_active = 0 "
                    + "AND (name LIKE ? OR phone LIKE ?) "
                    + "ORDER BY customer_id DESC";
            } else {
                sql = "SELECT customer_id, name, phone, address, is_active, created_at "
                    + "FROM Customers "
                    + "WHERE is_active = 1 "
                    + "AND (name LIKE ? OR phone LIKE ?) "
                    + "ORDER BY customer_id DESC";
            }

            try (Connection conn = com.mycompany.laundryservice.database.DBConnection.getConnection();
                 PreparedStatement ps = conn.prepareStatement(sql)) {

                String likeTerm = "%" + (searchTerm == null ? "" : searchTerm.trim()) + "%";
                ps.setString(1, likeTerm);
                ps.setString(2, likeTerm);

                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        model.addRow(new Object[]{
                            rs.getInt("customer_id"), rs.getString("name"), rs.getString("phone"),
                            rs.getString("address"), rs.getInt("is_active") == 1 ? "Active" : "Inactive",
                            rs.getTimestamp("created_at")
                        });
                    }
                }
                tblCustomers.setModel(model);
                formatCustomerTable();
                lblRecordCount.setText("Showing " + model.getRowCount() + " customers");

            } catch (SQLException e) {
                setStatus("Unable to connect to the database.", false);
            }
        }

        private void setStatus(String message, boolean success) {
            lblStatus.setForeground(success ? new Color(0x2E, 0x7D, 0x32) : new Color(0xBA, 0x1A, 0x1A));

             int maxChars = 40;
            String displayMessage = message.length() > maxChars
            ? message.substring(0, maxChars - 3) + "..."
            : message;
            lblStatus.setText(displayMessage);
            lblStatus.setToolTipText(message);
        }
        

        private void resetForm() {
            txtName.setText("");
            txtPhone.setText("");
            txtAddress.setText("");
            selectedCustomerId = -1;
            tblCustomers.clearSelection();
            btnUpdate.setEnabled(false);
            btnDeactivate.setEnabled(false);
            selectedIsActive = true;
            btnDeactivate.setText("Deactivate");
            btnDeactivate.setBackground(new Color(0xBA, 0x1A, 0x1A));
            
            editMode = false;

            lblRegisterHeader.setText("Register New Customer");
            btnSave.setText("Save Customer");
            btnSave.setIcon(loadIcon("save.svg", 18, 0x1A1C1C));
            
            lblRegisterHint.setText(
                "Fill in the customer information below."
            );
        }

private static class RoundedCardBorder extends javax.swing.border.AbstractBorder {
    private final int radius;
    private final Color fill;
    private final Color stroke;

    RoundedCardBorder(int radius, Color fill, Color stroke) {
        this.radius = radius;
        this.fill = fill;
        this.stroke = stroke;
    }

    @Override
    public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(java.awt.RenderingHints.KEY_STROKE_CONTROL, java.awt.RenderingHints.VALUE_STROKE_PURE);
        g2.setColor(fill);
        g2.fillRoundRect(x, y, width - 1, height - 1, radius, radius);
        g2.setColor(stroke);
        g2.setStroke(new java.awt.BasicStroke(1f));
        java.awt.geom.RoundRectangle2D.Float shape = new java.awt.geom.RoundRectangle2D.Float(
                x + 0.5f, y + 0.5f, width - 1.5f, height - 1.5f, radius, radius);
        g2.draw(shape);

        g2.dispose();
    }

    @Override
    public java.awt.Insets getBorderInsets(java.awt.Component c) {
        return new java.awt.Insets(0, 0, 0, 0);
    }
}
     
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        loadCustomers(txtSearch.getText());
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedCustomerId == -1) return;

        String name = txtName.getText().trim();
        String phone = txtPhone.getText().trim();
        String address = txtAddress.getText().trim();

        if (name.isEmpty() || phone.isEmpty()) {
            setStatus("Please fill in all required fields.", false);
            return;
        }

        String checkSql = "SELECT COUNT(*) FROM Customers WHERE phone = ? AND customer_id <> ?";
        String updateSql = "UPDATE Customers SET name = ?, phone = ?, address = ? WHERE customer_id = ?";

        try (Connection conn = com.mycompany.laundryservice.database.DBConnection.getConnection()) {
            try (PreparedStatement check = conn.prepareStatement(checkSql)) {
                check.setString(1, phone);
                check.setInt(2, selectedCustomerId);
                try (ResultSet rs = check.executeQuery()) {
                    rs.next();
                    if (rs.getInt(1) > 0) {
                        setStatus("This phone number belongs to another customer.", false);
                        return;
                    }
                }
            }
            try (PreparedStatement update = conn.prepareStatement(updateSql)) {
                update.setString(1, name);
                update.setString(2, phone);
                update.setString(3, address.isEmpty() ? null : address);
                update.setInt(4, selectedCustomerId);
                update.executeUpdate();
            }
            resetForm();
            loadCustomers(txtSearch.getText());
            setStatus("Customer updated successfully.", true);
        } catch (SQLException e) {
            setStatus("Unable to connect to the database.", false);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        loadCustomers(txtSearch.getText());
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        if (editMode) {
            btnUpdateActionPerformed(evt);
            return;
        }
        
        String name = txtName.getText().trim();
        String phone = txtPhone.getText().trim();
        String address = txtAddress.getText().trim();

        if (name.isEmpty() || phone.isEmpty()) {
            setStatus("Please fill in all required fields.", false);
            return;
        }

        String checkSql = "SELECT COUNT(*) FROM Customers WHERE phone = ?";
        String insertSql = "INSERT INTO Customers (name, phone, address) VALUES (?, ?, ?)";

        try (Connection conn = com.mycompany.laundryservice.database.DBConnection.getConnection()) {
            try (PreparedStatement check = conn.prepareStatement(checkSql)) {
                check.setString(1, phone);
                try (ResultSet rs = check.executeQuery()) {
                    rs.next();
                    if (rs.getInt(1) > 0) {
                        setStatus("This phone number is already registered.", false);
                        return;
                    }
                }
            }
            try (PreparedStatement insert = conn.prepareStatement(insertSql)) {
                insert.setString(1, name);
                insert.setString(2, phone);
                insert.setString(3, address.isEmpty() ? null : address);
                insert.executeUpdate();
            }
            resetForm();
            loadCustomers(txtSearch.getText());
            updateCustomerCount();
            setStatus("Customer saved successfully.", true);
        } catch (SQLException e) {
            setStatus("Unable to connect to the database.", false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
         if (selectedCustomerId == -1) return;
        boolean activate = !selectedIsActive;
        String action = activate ? "activate" : "deactivate";

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to " + action + " this customer?",
                "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        String sql = "UPDATE Customers SET is_active = ? WHERE customer_id = ?";
        try (Connection conn = com.mycompany.laundryservice.database.DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, activate ? 1 : 0);
            ps.setInt(2, selectedCustomerId);
            ps.executeUpdate();

            resetForm();
            loadCustomers(txtSearch.getText());
            updateCustomerCount();
            setStatus(activate ? "Customer activated successfully." : "Customer deactivated successfully.", true);
        } catch (SQLException e) {
            setStatus("Unable to connect to the database.", false);
        }
    }//GEN-LAST:event_btnDeactivateActionPerformed

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        char C = evt.getKeyChar();
        if(!Character.isDigit(C)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneKeyTyped

    private void btnDeactivatedAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivatedAccountsActionPerformed
         showingDeactivated = !showingDeactivated;
    resetForm();
    loadCustomers(txtSearch.getText());
    updateCustomerCount();
    btnDeactivatedAccounts.setText(showingDeactivated ? "Show Active Accounts" : "Show Deactivated Accounts");
    }//GEN-LAST:event_btnDeactivatedAccountsActionPerformed
    private void updateCustomerCount() {
        String sql;

        if (showingDeactivated) {
            sql = "SELECT COUNT(*) FROM Customers WHERE is_active = 0";
        } else {
            sql = "SELECT COUNT(*) FROM Customers WHERE is_active = 1";
        }

        try (Connection conn = com.mycompany.laundryservice.database.DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            if (rs.next()) {
                lblTotalCustomersValue.setText(
                    java.text.NumberFormat.getIntegerInstance().format(rs.getInt(1))
                );
            }

        } catch (SQLException e) {
            setStatus("Unable to count customers.", false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnDeactivatedAccounts;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAddressCaption;
    private javax.swing.JLabel lblNameCaption;
    private javax.swing.JLabel lblPhoneCaption;
    private javax.swing.JLabel lblRecordCount;
    private javax.swing.JLabel lblRegisterHeader;
    private javax.swing.JLabel lblRegisterHint;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCustomersCaption;
    private javax.swing.JLabel lblTotalCustomersValue;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlRegisterCard;
    private javax.swing.JPanel pnlSearchBar;
    private javax.swing.JPanel pnlStats;
    private javax.swing.JPanel pnlTableCard;
    private javax.swing.JScrollPane scrollCustomers;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
