/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laundryservice.panels;

import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.laundryservice.MainJFrame;
import javax.swing.JFrame;

/**
 *
 * @author Cral
 */
public class HomePanel extends javax.swing.JPanel {

	/**
	 * Creates new form HomePanel
	 */
	public HomePanel() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pnlHeader = new javax.swing.JPanel();
                pnlBody = new javax.swing.JPanel();
                pnlMetrics = new javax.swing.JPanel();
                pnlTable = new javax.swing.JPanel();

                setBackground(new java.awt.Color(249, 249, 249));
                setLayout(new java.awt.BorderLayout());

                javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
                pnlHeader.setLayout(pnlHeaderLayout);
                pnlHeaderLayout.setHorizontalGroup(
                        pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1003, Short.MAX_VALUE)
                );
                pnlHeaderLayout.setVerticalGroup(
                        pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                add(pnlHeader, java.awt.BorderLayout.NORTH);

                pnlBody.setLayout(new java.awt.BorderLayout());

                javax.swing.GroupLayout pnlMetricsLayout = new javax.swing.GroupLayout(pnlMetrics);
                pnlMetrics.setLayout(pnlMetricsLayout);
                pnlMetricsLayout.setHorizontalGroup(
                        pnlMetricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1003, Short.MAX_VALUE)
                );
                pnlMetricsLayout.setVerticalGroup(
                        pnlMetricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                pnlBody.add(pnlMetrics, java.awt.BorderLayout.NORTH);

                javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
                pnlTable.setLayout(pnlTableLayout);
                pnlTableLayout.setHorizontalGroup(
                        pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1003, Short.MAX_VALUE)
                );
                pnlTableLayout.setVerticalGroup(
                        pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 462, Short.MAX_VALUE)
                );

                pnlBody.add(pnlTable, java.awt.BorderLayout.CENTER);

                add(pnlBody, java.awt.BorderLayout.CENTER);
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel pnlBody;
        private javax.swing.JPanel pnlHeader;
        private javax.swing.JPanel pnlMetrics;
        private javax.swing.JPanel pnlTable;
        // End of variables declaration//GEN-END:variables

    public void setMainFrame(MainJFrame aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
