/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laundryservice.panels;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JFrame;

/**
 *
 * @author Cral
 */
public class HomePanel extends javax.swing.JPanel {

	/**
	 * Creates new form HomePanel
	 */
	public HomePanel() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                homePageTitle = new javax.swing.JLabel();
                homeSectionTitle = new javax.swing.JLabel();

                setBackground(new java.awt.Color(249, 249, 249));

                homePageTitle.setFont(new java.awt.Font("Inter 28pt", 0, 22)); // NOI18N
                homePageTitle.setForeground(new java.awt.Color(28, 28, 28));
                homePageTitle.setText("Operations Overview");

                homeSectionTitle.setFont(new java.awt.Font("Inter 18pt", 0, 11)); // NOI18N
                homeSectionTitle.setForeground(new java.awt.Color(67, 70, 105));
                homeSectionTitle.setText("Today's Overview and recent activity");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(homePageTitle)
                                        .addComponent(homeSectionTitle))
                                .addContainerGap(770, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(homePageTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(homeSectionTitle)
                                .addContainerGap(590, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel homePageTitle;
        private javax.swing.JLabel homeSectionTitle;
        // End of variables declaration//GEN-END:variables
}
