package com.mycompany.laundryservice.panels;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Cral
 */
public class SidebarPanel extends javax.swing.JPanel {

	/**
	 * Creates new form SidebarPanel
	 */
	public SidebarPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                sidebarTitle = new javax.swing.JLabel();
                sidebarAddress = new javax.swing.JLabel();

                setBackground(new java.awt.Color(43, 89, 195));
                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

                sidebarTitle.setBackground(new java.awt.Color(255, 255, 255));
                sidebarTitle.setFont(new java.awt.Font("Playfair Display", 0, 18)); // NOI18N
                sidebarTitle.setForeground(new java.awt.Color(255, 255, 255));
                sidebarTitle.setText("Laundry Service");
                add(sidebarTitle);

                sidebarAddress.setForeground(new java.awt.Color(255, 255, 255));
                sidebarAddress.setText("Ligao City, Albay");
                add(sidebarAddress);
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel sidebarAddress;
        private javax.swing.JLabel sidebarTitle;
        // End of variables declaration//GEN-END:variables
}
